### ISSUE TITLE
Bing国际版重定向无效

### ISSUE THREAD

**Issue by Maritedo** [AirBashX/UserScript#16]
[这一处提交(第361行)](https://github.com/AirBashX/UserScript/commit/1741ec54d489e9f9d591f5eaa0a48475cdfeb9a9#diff-50658b8b59878ffe2572687f897030325d65cbb14f4acff78a93fe09850a66ddR361) 存在错误：
`cite` 并不包含 `includes` 方法，这导致 `v1.3.21` 版本的 `LinkManager.user.js` 的重定向功能在 [www.bing.com](https://www.bing.com) 上失效了。

应该将此处的
```js
if (!cite.includes("...")) {
    a.href = cite.innerHTML;
}
```
替换为
```js
if (!cite.innerHTML.includes("...")) {
    a.href = cite.innerHTML;
}
```

**Comment by AirBashX** [comment]
抱歉刚看到,你是对的,这里确实出问题了
