### ISSUE TITLE
简书登录弹窗拦截

### ISSUE THREAD

**Issue by ySirius** [AirBashX/UserScript#21]
name: "简书",
url: "jianshu.com",
items: [
  //下载弹窗
  ".download-app-guidance",
  //悬浮按钮:打开App,看更多相似好文
  ".call-app-btn",
  //悬浮按钮:打开App,看更多好文(首页)
  ".index_call-app-btn",
  "._23ISFX-mask",
  "._23ISFX-content",
],

好像是加上后面两个有效，不知道是不是只针对我

**Comment by AirBashX** [comment]
您是在什么环境下使用的什么浏览器?我这并没显示任何弹窗

**Comment by AirBashX** [comment]
新版本已更新,该问题已解决
