### ISSUE TITLE
使用bing会出现替换搜索项导致无法正常打开网页

### ISSUE THREAD

**Issue by 892050179** [AirBashX/UserScript#22]
https://github.com/AirBashX/UserScript/blob/98269fbe4a01d63a59b5f2751675975f9c2f1465/LinkManager.user.js#L424
该位置存在错误导致使用bing替换的搜索项无法正常打开网页。
应该把此处的替换为
`a.href = cite.innerText;`

使用bing国内版没有重定向，可判断`#est_cn`是否为选中状态，若非选中状态可以不做处理

**Comment by AirBashX** [comment]
目前更新了新版本,国外版应该是没问题了,后续会采取你这个方案
